# Generated by Django 3.0.3 on 2020-04-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=150)),
                ('producttype', models.CharField(max_length=150)),
                ('product', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('size', models.CharField(max_length=150)),
            ],
        ),
    ]
