# Generated by Django 3.0.3 on 2020-04-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=10)),
                ('prodcuttype', models.CharField(max_length=10)),
                ('product', models.CharField(max_length=10)),
                ('price', models.IntegerField(max_length=10)),
                ('size', models.CharField(max_length=10)),
            ],
        ),
    ]
